about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/includes/card_author.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
        <div class="card-body">
            <div class="h2">
                {{ posts.author.get_full_name }}
            </div>
            <div class="h3 text-muted">
                {{ post.author }}
            </div>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Подписчиков: {{ author.following.count }} <br/>
                    Подписан: {{ author.follower.count }}
                </div>
            </li>
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Записей: {{ author.posts.count }}
                </div>
            </li>
            {% if request.user != author %}
            <li class="list-group-item">
                {% if following %}
                <a class="btn btn-lg btn-light"
                   href="{% url 'profile_unfollow' author.username %}"
                   role="button">
                    Отписаться
                </a>
                {% else %}
                <a class="btn btn-lg btn-primary"
                   href="{% url 'profile_follow' author.username %}"
                   role="button">
                    Подписаться
                </a>
                {% endif %}
            </li>
            {% endif %}
        </ul>
    </div>
</div>

templates/includes/card_post.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "1100" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="card-body">
        <p class="card-text">
            <a href="{% url 'profile' author %}"><strong
                    class="d-block text-gray-dark">@{{ post.author }}</strong></a>
            {{ post.text }}
        </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
                {% if request.user == user %}
                <a class="btn btn-sm text-muted"
                   href="{% url 'add_comment' username=request.user post_id=post.id  %}"
                   role="button">Добавить комментарий</a>
                {% endif %}
                {% if request.user == author %}
                <a class="btn btn-sm text-muted"
                   href="{% url 'post_edit' username=post.author post_id=post.id  %}"
                   role="button">Редактировать</a>
                {% endif %}
            </div>
            <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>
        </div>
    </div>
</div>

templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
{% block content %}

<main role="main" class="container">
    <div class="row justify-content-center">
        <div class="card my-4">
            <form method="post"
                  action="{% url 'add_comment' post.author.username post.id %}">
                {% csrf_token %}
                <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
                    <div class="form-group">
                        {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить
                    </button>
                </div>
            </form>
        </div>
        <!-- Комментарии -->
        {% for comment in post.comments.all %}
        <div class="col-md-6 offset-md-4">
            <div class="media-body card-body">
                <h5 class="mt-0">
                    <a href="{% url 'profile' comment.author.username %}"
                       name="comment_{{ comment.id }}">
                        {{ comment.author.username }}
                    </a>
                </h5>
                <p>{{ comment.text | linebreaksbr }}</p>
                <hr>
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% include "includes/paginator.html" %}
            </div>
        </div>
        {% endfor %}
</main>
{% endblock %}
{% endif %}

templates/includes/follow.html
{% extends "base.html" %}
{% block title %} Последние обновления ваших подписок {% endblock %}

{% block content %}
<div class="container">

    {% include "menu.html" with index=True %}

    <h1> Последние обновления ваших подписок</h1>
    <!-- Вывод ленты записей -->
    {% load cache %}
    {% cache 20 index_page page %}
    {% for post in page %}
    <!-- Вот он, новый include! -->
    {% include 'includes/post_item.html' with post=post %}
    {% endfor %}
    {% endcache %}
</div>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}
{% endif %}
{% if page.has_other_pages %}
{% include "includes/paginator.html" with items=page paginator=paginator%}
{% endif %}
{% endblock %}

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
     <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технология</a>
    Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer>

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
            Пользователь: {{ user.username }}
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
    {% load thumbnail %}
    {% thumbnail post.image "1100" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}"/>
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
        <p class="card-text">
            <!-- Ссылка на автора через @ -->
            <a name="post_{{ post.id }}"
               href="{% url 'profile' post.author.username %}">
                <strong class="d-block text-gray-dark">@{{post.author}}</strong>
            </a>
            {{ post.text|linebreaksbr }}
        </p>

        <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
        {% if post.group %}
        <a class="card-link muted"
           href="{% url 'group_posts' post.group.slug %}">
            <strong class="d-block text-gray-dark">#{{post.group.title}}</strong>
        </a>
        {% endif %}

        <!-- Отображение ссылки на комментарии -->
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                {% if post.comments.exists %}
                <div>
                    Комментариев: {{ post.comments.count }}
                </div>
                {% endif %}
                <a class="btn btn-sm btn-primary"
                   href="{% url 'add_comment' post.author.username post.id %}"
                   role="button">
                    Добавить комментарий
                </a>

                <!-- Ссылка на редактирование поста для автора -->
                {% if user == post.author %}
                <a class="btn btn-sm btn-info"
                   href="{% url 'post_edit' post.author.username post.id %}"
                   role="button">
                    Редактировать
                </a>
                {% endif %}
            </div>

            <!-- Дата публикации поста -->
            <small class="text-muted">{{ post.pub_date }}</small>
        </div>
    </div>
</div>
{% if show_comment %}
{% include 'includes/comments.html' %}
{% endif %}